### ISSUE TITLE
Login button should be wider

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsman#6]
In the Login page, the Login button is too small, it should be wider. This doesn't happen in the Sign Up page, where the Sign Up button has the correct width.

<img width="554" alt="screen shot 2017-01-31 at 15 42 08" src="https://cloud.githubusercontent.com/assets/7082300/22469374/0d101662-e7cc-11e6-9596-e6fcb12f7ed0.png">

**Comment by javierartero** [comment]
https://github.com/MarsBased/marsman/pull/24

**Comment by javierartero** [comment]
https://github.com/MarsBased/marsman/pull/24
