### ISSUE TITLE
In login boxes where there is no subtitle, the title should be aligned at the center of the header

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsman#8]
Our Login type of pages (Login, Sign Up, Forgot Password) have a title and a subtitle. However, if we want to have just one title, without subtitle, the title should look centered at the middle of the header.

<img width="555" alt="screen shot 2017-01-31 at 15 45 31" src="https://cloud.githubusercontent.com/assets/7082300/22469496/81b8edd6-e7cc-11e6-9a99-44d842fd7758.png">

**Comment by javierartero** [comment]
https://github.com/MarsBased/marsman/pull/24
